#!/bin/bash
#
# Bloodhound — first boot of a freshly deployed OVA.
#
# Run once by bloodhound-firstboot.service, only when the marker file left by
# factory-reset.sh exists. Generates everything that must be unique per
# appliance, so no two customer deployments share a secret:
#   - SSH host keys
#   - Graylog root password + password_secret  (→ syslog-platform/.env)
#   - Self-signed TLS certificate for nginx
# The Bloodhound JWT secret is generated by the backend itself on first start
# (Redis was flushed by factory-reset.sh). /etc/machine-id is regenerated by
# systemd because factory-reset.sh truncates it.
#
set -euo pipefail

PROJECT_DIR="/opt/bloodhound/syslog-platform"
ENV_FILE="$PROJECT_DIR/.env"
BACKEND_ENV_FILE="$PROJECT_DIR/backend/.env"
SSL_DIR="/opt/bloodhound/ssl"
MARKER="/opt/bloodhound/.firstboot"
GRAYLOG_PW_FILE="/opt/bloodhound/graylog-admin-password"

log() { echo "[firstboot] $*"; }

# Replace KEY=... in an env file, or append it. Values are generated
# alphanumeric strings, so no sed escaping is needed.
set_env_var() {
    local file="$1" key="$2" value="$3"
    touch "$file"
    if grep -q "^${key}=" "$file"; then
        sed -i "s|^${key}=.*|${key}=${value}|" "$file"
    else
        echo "${key}=${value}" >> "$file"
    fi
}

# No `tr < /dev/urandom | head` here: with pipefail, tr's SIGPIPE aborts the script.
rand_alnum() {
    local s
    s="$(openssl rand -base64 $(( $1 * 2 )) | tr -dc 'A-Za-z0-9')"
    echo "${s:0:$1}"
}

# ── SSH host keys ──────────────────────────────────────────────────────────
log "Generating SSH host keys"
rm -f /etc/ssh/ssh_host_*
ssh-keygen -A

# ── Graylog secrets ────────────────────────────────────────────────────────
log "Generating Graylog secrets"
GRAYLOG_PASSWORD="$(rand_alnum 24)"
GRAYLOG_SHA2="$(echo -n "$GRAYLOG_PASSWORD" | sha256sum | cut -d' ' -f1)"
GRAYLOG_SECRET="$(rand_alnum 96)"

set_env_var "$ENV_FILE" GRAYLOG_PASSWORD           "$GRAYLOG_PASSWORD"
set_env_var "$ENV_FILE" GRAYLOG_ROOT_PASSWORD_SHA2 "$GRAYLOG_SHA2"
set_env_var "$ENV_FILE" GRAYLOG_PASSWORD_SECRET    "$GRAYLOG_SECRET"
# The backend talks to the Graylog API with the same account
set_env_var "$BACKEND_ENV_FILE" GRAYLOG_PASSWORD   "$GRAYLOG_PASSWORD"
chmod 600 "$ENV_FILE" "$BACKEND_ENV_FILE"
chown bloodhound:bloodhound "$ENV_FILE" "$BACKEND_ENV_FILE"

umask 077
echo "$GRAYLOG_PASSWORD" > "$GRAYLOG_PW_FILE"
umask 022

# ── TLS certificate ────────────────────────────────────────────────────────
log "Generating self-signed TLS certificate"
mkdir -p "$SSL_DIR"
HOST="$(hostname)"
openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
    -keyout "$SSL_DIR/bloodhound.key" \
    -out    "$SSL_DIR/bloodhound.crt" \
    -subj   "/O=Bloodhound/CN=$HOST" \
    -addext "subjectAltName=DNS:$HOST,DNS:bloodhound.local" 2>/dev/null
chmod 600 "$SSL_DIR/bloodhound.key"

# ── Apply the new Graylog secrets ─────────────────────────────────────────
# Containers restarted by Docker's restart policy keep the environment they
# were created with; `up -d` recreates those whose configuration changed.
log "Recreating containers with the new secrets"
cd "$PROJECT_DIR"
docker compose up -d

# ── Done ───────────────────────────────────────────────────────────────────
rm -f "$MARKER"
log "First boot complete. Graylog admin password: sudo cat $GRAYLOG_PW_FILE"
