#!/usr/bin/env bash
# Bloodhound — install or upgrade from this package.
#
#   sudo ./install.sh            # install (or upgrade: data and settings are kept)
#
# Options (environment variables, rarely needed):
#   BH_DIR=/opt/bloodhound       installation directory
#   BH_WAIT=600                  seconds to wait for the application to start
set -euo pipefail

PKG="$(cd "$(dirname "$0")" && pwd)"
VERSION="$(cat "$PKG/VERSION")"
DIR="${BH_DIR:-/opt/bloodhound}"

say()  { printf '\033[1;33m==>\033[0m %s\n' "$*"; }
ok()   { printf '\033[1;32m ok\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || exec sudo -E "$0" "$@"
[ "$(uname -m)" = "x86_64" ] || die "this package is for x86_64 (amd64) Linux; this host is $(uname -m)"

echo
echo "  Bloodhound $VERSION — installation in $DIR"
echo

# --- Docker ------------------------------------------------------------------------------
if ! command -v docker >/dev/null 2>&1; then
  if command -v apt-get >/dev/null 2>&1; then
    say "Installing Docker from the distribution packages (docker.io, docker-compose-v2)"
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -qq
    apt-get install -y -qq docker.io docker-compose-v2 >/dev/null || die "Docker installation failed"
    systemctl enable --now docker >/dev/null 2>&1 || true
  else
    die "Docker is not installed. Install Docker Engine and the Compose plugin, then run again."
  fi
fi
docker compose version >/dev/null 2>&1 || die "Docker Compose v2 is missing (package docker-compose-v2)"
ok "$(docker --version | cut -d, -f1)"

UPGRADE=0
[ -f "$DIR/.env" ] && UPGRADE=1
if [ "$UPGRADE" = 1 ]; then
  say "Existing installation found ($(grep '^APP_VERSION=' "$DIR/.env" | cut -d= -f2)): upgrade to $VERSION, data and settings kept"
else
  for p in 443/tcp 80/tcp 514/udp 514/tcp; do
    n=${p%/*}; proto=${p#*/}
    if ss -lnH "$( [ "$proto" = udp ] && echo -u || echo -t )" "sport = :$n" 2>/dev/null | grep -q .; then
      die "port $p is already used on this host"
    fi
  done
fi

# --- kernel settings ------------------------------------------------------------------------
# OpenSearch refuses to start below this value; larger UDP buffers for syslog bursts.
cat > /etc/sysctl.d/90-bloodhound.conf <<'EOF'
vm.max_map_count = 262144
net.core.rmem_max = 33554432
net.core.rmem_default = 8388608
EOF
sysctl -q --system >/dev/null 2>&1 || true

# --- images ------------------------------------------------------------------------------
say "Loading the images (a few minutes)"
gunzip -c "$PKG/images.tar.gz" | docker load -q >/dev/null
ok "images loaded"

# --- files and configuration ---------------------------------------------------------------
install -d -m 755 "$DIR" "$DIR/graylog"
install -m 644 "$PKG/compose.yml" "$DIR/compose.yml"
install -m 644 "$PKG/VERSION" "$DIR/VERSION"
install -m 755 "$PKG/graylog-bootstrap.sh" "$DIR/graylog-bootstrap.sh"
install -m 644 "$PKG/QUICKSTART.md" "$DIR/QUICKSTART.md"
[ -f "$PKG/LICENSE" ] && install -m 644 "$PKG/LICENSE" "$DIR/LICENSE"
install -m 644 "$PKG"/graylog/* "$DIR/graylog/"

IP="$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src") print $(i+1)}' | head -1)"
IP="${IP:-$(hostname -I | awk '{print $1}')}"

if [ "$UPGRADE" = 0 ]; then
  # finite input: no SIGPIPE under pipefail
  rnd() { head -c 2048 /dev/urandom | LC_ALL=C tr -dc 'A-Za-z0-9' | cut -c "1-$1"; }
  GRAYLOG_PASSWORD="$(rnd 24)"
  TZ_NAME="$(timedatectl show -p Timezone --value 2>/dev/null || echo UTC)"
  # OpenSearch heap: a quarter of the RAM, between 1 and 8 GB
  MEM_GB=$(( $(awk '/MemTotal/ {print $2}' /proc/meminfo) / 1024 / 1024 ))
  HEAP=$(( MEM_GB / 4 )); [ "$HEAP" -lt 1 ] && HEAP=1; [ "$HEAP" -gt 8 ] && HEAP=8
  umask 077
  cat > "$DIR/.env" <<EOF
# Bloodhound configuration — generated by install.sh on $(date -u +%F).
# Change a value, then: cd $DIR && sudo docker compose up -d
APP_VERSION=$VERSION
APP_TIMEZONE=${TZ_NAME:-UTC}
OPENSEARCH_HEAP=${HEAP}g
TLS_COMMON_NAME=$(hostname)
TLS_EXTRA_SAN=IP:$IP
# Graylog admin account (UI on 127.0.0.1:9000, SSH tunnel) — unique per install
GRAYLOG_PASSWORD=$GRAYLOG_PASSWORD
GRAYLOG_ROOT_PASSWORD_SHA2=$(printf '%s' "$GRAYLOG_PASSWORD" | sha256sum | cut -d' ' -f1)
GRAYLOG_PASSWORD_SECRET=$(rnd 96)
EOF
  umask 022
  ok "configuration written to $DIR/.env (unique secrets)"
else
  sed -i "s/^APP_VERSION=.*/APP_VERSION=$VERSION/" "$DIR/.env"
fi
chmod 600 "$DIR/.env"

# --- start -------------------------------------------------------------------------------
say "Starting"
cd "$DIR"
docker compose up -d --remove-orphans >/dev/null 2>&1 || docker compose up -d --remove-orphans

WAIT="${BH_WAIT:-600}"
for i in $(seq 1 $((WAIT / 5))); do
  # 401 = backend up and protecting the API
  code="$(curl -sk -o /dev/null -w '%{http_code}' https://127.0.0.1/api/v1/auth/me 2>/dev/null || true)"
  [ "$code" = 401 ] || [ "$code" = 200 ] && break
  [ "$i" = $((WAIT / 5)) ] && die "the application did not become ready in $((WAIT / 60)) minutes: cd $DIR && sudo docker compose logs"
  sleep 5
done
ok "web interface and API running"

say "Configuring Graylog (syslog input, Ruckus parsing rule, stream)"
"$DIR/graylog-bootstrap.sh" || die "Graylog configuration failed: run sudo $DIR/graylog-bootstrap.sh again"

echo
echo "  ────────────────────────────────────────────────────────────────────"
echo "   Bloodhound $VERSION is ready"
echo
echo "   Web interface   https://$IP/"
echo "                   (self-signed certificate: accept the browser warning)"
if [ "$UPGRADE" = 0 ]; then
  echo "   User            bloodhound"
  echo "   Password        password   (change it now: Settings → Password)"
fi
echo
echo "   Syslog          point the APs / controller to $IP, UDP 514"
echo "   Graylog UI      ssh -L 9000:localhost:9000 <user>@$IP  then http://localhost:9000"
echo "                   user admin, password: sudo grep GRAYLOG_PASSWORD= $DIR/.env"
echo "   Files           $DIR"
echo "  ────────────────────────────────────────────────────────────────────"
echo
